apiVersion: v1
kind: Service
metadata:
  name: lobsters-sql
  labels:
    app: lobsters
    tier: db
spec:
  ports:
  - port: 3306
    targetPort: sql
  selector:
    app: lobsters
    tier: db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: lobsters
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lobsters-sql
  labels:
    app: lobsters
    tier: db
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lobsters
        tier: db
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: password
        ports:
        - containerPort: 3306
          name: sql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
