apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume9
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
      storage: 5Gi
  hostPath:
      path: "/data/volume9"
